<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HardwareGuardian.Infrastructure</RootNamespace>
    <AssemblyName>HardwareGuardian.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardwareGuardian.Core\HardwareGuardian.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" />
    <PackageReference Include="Microsoft.Win32.Registry" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
