<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>WindowsMaintenanceCenter.Infrastructure</RootNamespace>
    <AssemblyName>WindowsMaintenanceCenter.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsMaintenanceCenter.Core\WindowsMaintenanceCenter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" />
    <PackageReference Include="Microsoft.Win32.Registry" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
