<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>WindowsMaintenanceCenter.Security</RootNamespace>
    <AssemblyName>WindowsMaintenanceCenter.Security</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsMaintenanceCenter.Core\WindowsMaintenanceCenter.Core.csproj" />
  </ItemGroup>

</Project>
