<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HardwareGuardian.Maintenance</RootNamespace>
    <AssemblyName>HardwareGuardian.Maintenance</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardwareGuardian.Core\HardwareGuardian.Core.csproj" />
  </ItemGroup>

</Project>
